export const LOADING_STATUS = 'LOADING_STATUS';

export const MARKETPAIR_UPDATED = 'MARKETPAIR_UPDATED';

export const ORDERBOOK_LOADED = 'ORDERBOOK_LOADED';

export const ORDERBOOK_UPDATED = 'ORDERBOOK_UPDATED';

export const AGGTRADE_UPDATED = 'AGGTRADE_UPDATED';

export const AGGTRADE_LOADED = 'AGGTRADE_LOADED';
